Add required system.text.json package
2>FilesystemBrowser.cs(13,19): Error KTSU0006 : Type or member from transitive package 'System.Text.Json' is used directly; add a PackageReference to 'System.Text.Json'